# Swagger definition for the TranscodeE16 Manifest
swagger: '2.0'

# Metadata
info:
  version: "1.0.0"
  title: PDB Aggregator
  description: 'An aggregator that buys data from nodes in the Personal Data Broker network.'
  termsOfService: https://opensource.org/licenses/MIT
  contact:
    email: fred@PageKicker.com
    name: Fred Zimmerman
    url: https://www.PageKicker.com
  x-21-usage: 'Buy personal data from participants in the network..'
  x-21-quick-buy: "$ 21 buy AUTO:5018 --data '{\"nodes\": "all", \"data set name\": \"interests\"}'"
  x-21-category: utilities
  x-21-github-profile-url: https://github.com/pooleja
  x-21-github-project-url: https://github.com/pooleja/Ping21AggregatorE16
  x-21-keywords: [marketing, advertising, revenue, sales]
  x-21-total-price:
     min: 1000
     max: 10000000
host: TK
schemes:
   - http
basePath: /
x-21-manifest-path: /manifest

# Available paths for the app
paths:
  /buy/<data set name>/<users>:
    get:
      description: Buys selected data set from selected users in network.
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successfully found all JSON data sets and returned them to client.
